statusHeroUsername: 'my-username'
statusHeroPassword: 'my-password'
gitAuthor: 'My author name from .gitconfig'
gitDirectories:
  - ~/path/to/your/project
  - ~/path/to/another/project
willSubmit: false
willRunHeadless: false
